#! /bin/sh

set -u
set -o pipefail
set -e

BEAM_DIR=${SIN_joxa_DIR}/ebin
JXA_OUT=$BEAM_DIR
SRC_DIR=${SIN_joxa_DIR}/src

mkdir -p ${JXA_OUT}

echo Building ${SIN_joxa_DIR}/src/joxa/compiler.jxa to ${JXA_OUT}

erl -pa $BEAM_DIR -noshell -s jxa_compile main -s init stop \
     -extra  -o ${JXA_OUT} ${SIN_joxa_DIR}/src/joxa/compiler.jxa

 # echo Building the compiler with itself
 # erl -pa $BEAM_DIR -noshell -s joxa.compiler main -s init stop \
 #      -extra  -o ${JXA_OUT} ${SIN_joxa_DIR}/src/joxa/compiler.jxa
